Eswe 415 create unit test for education api
ministryofjustice/hmpps-education-employment-api pull request #20
Opened 2022-10-18 08:15 UTC by sacintha

2022-10-19 10:02 UTC, theDustRoom requested changes
As these are standard endpoint checks used within HMPPS projects we need to ensure that these health and info endpoints are functioning as expected so the tests should be in place to ensure this.

2022-10-24 13:08 UTC, sacintha commented on src/test/kotlin/uk/gov/justice/digital/hmpps/educationemploymentapi/integration/IntegrationTestBase.kt
> +  /*internal fun setAuthorisation(
I have removed the comment

2022-10-24 13:08 UTC, sacintha commented on src/test/kotlin/uk/gov/justice/digital/hmpps/educationemploymentapi/integration/health/HealthCheckTest.kt
> +  /* @Test  @Test
I have added them

2022-10-24 13:09 UTC, sacintha commented on src/test/kotlin/uk/gov/justice/digital/hmpps/educationemploymentapi/integration/health/InfoTest.kt
> + /* @Test
I have added them

2022-10-24 13:16 UTC, merged